main: StrellaMC.MuchDan.ToggleChatColor.ToggleChatColor
name: SetChatColor
author: MuchDan
version: 0.0.0
api-version: 1.16
description: Toggle your chat color!

commands:
  setChat:
    permission: StrellaMC.setChat.toggle
    permission-message: "You don't have permission to do that!"